name: CI

on:
  push:
    branches: [ freebsd-ci ]

jobs:
  build-test-freebsd:
    runs-on: [self-hosted, freebsd]

    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap build system
        run: autoreconf -fvi

      - name: Configure
        run: |
          ./configure --enable-lua \
            CFLAGS='-g -O2 -Wno-pointer-sign' \
            --with-test-socket=unix:/tmp/opendkim-test.sock

      - name: Build
        run: gmake -j$(sysctl -n hw.ncpu)

      - name: Test
        run: gmake check

  build-test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y \
            autoconf automake libtool pkg-config \
            libssl-dev libmilter-dev \
            lua5.4 liblua5.4-dev

      - name: Bootstrap build system
        run: autoreconf -fvi

      - name: Configure
        run: |
          ./configure --enable-lua \
            CFLAGS='-g -O2 -Wno-pointer-sign'

      - name: Build
        run: make -j$(nproc)

      - name: Test
        run: make check
